### ISSUE TITLE
npm install issues with sqlite3 (resolved with 4.0.0)

### ISSUE THREAD

**Issue by grooverdan** [MeasureOSS/Measure#98]
<pre>
(py36) [dan@volution Measure]$ pip install nodeenv
Requirement already satisfied: nodeenv in /home/dan/py36/lib/python3.6/site-packages
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(py36) [dan@volution Measure]$ nodeenv ~/node_env
 * Install prebuilt node (10.4.0) ..... done.
(py36) [dan@volution Measure]$ source ~/node_env/bin/activate
(node_env)(py36) [dan@volution Measure]$ npm install

> sqlite3@3.1.9 install /home/dan/repos/Measure/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.9/node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.9 and node@10.4.0 (node-v64 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.9/node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.9 and node@10.4.0 (node-v64 ABI) (falling back to source compile with node-gyp) 
make: Entering directory '/home/dan/repos/Measure/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
make: Entering directory '/home/dan/repos/Measure/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: In function ‘strftimeFunc’:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:11909:27: warning: cast between incompatible function types from ‘int (*)(void *)’ to ‘void (*)(void *)’ [-Wcast-function-type]
 #define SQLITE_DYNAMIC   ((sqlite3_destructor_type)sqlite3MallocSize)
                           ^
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:19615:52: note: in expansion of macro ‘SQLITE_DYNAMIC’
                       z==zBuf ? SQLITE_TRANSIENT : SQLITE_DYNAMIC);
                                                    ^~~~~~~~~~~~~~
(.... many compile warnings ....)
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c: At top level:
Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:199451:1: fatal error: opening dependency file ./Release/.deps/Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o.d.raw: No such file or directory
 }
 ^
compilation terminated.
make: *** [deps/sqlite3.target.mk:127: Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o] Error 1
make: Leaving directory '/home/dan/repos/Measure/node_modules/sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/dan/node_env/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.16.11-300.fc28.x86_64
gyp ERR! command "/home/dan/node_env/bin/node" "/home/dan/node_env/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/dan/repos/Measure/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/dan/repos/Measure/node_modules/sqlite3/lib/binding/node-v64-linux-x64"
gyp ERR! cwd /home/dan/repos/Measure/node_modules/sqlite3
gyp ERR! node -v v10.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-gyp[7960]: ../src/node.cc:4012:void node::PlatformExit(): Assertion `(err) != (-1)' failed.
 1: node::Abort() [node-gyp]
 2: 0x893875 [node-gyp]
 3: 0x897872 [node-gyp]
 4: 0x7fd988d6366c [/lib64/libc.so.6]
 5: 0x7fd988d6379c [/lib64/libc.so.6]
 6: 0x893a94 [node-gyp]
 7: 0xb00af9 [node-gyp]
 8: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node-gyp]
 9: 0x1f2363b041bd
</pre>

Changing ```package.json``` to ```"sqlite3": "^4.0.0",``` appears to solve the problem.

**Comment by stuartlangridge** [comment]
I may be misunderstanding this issue, but this looks like a problem with the sqlite library generally, rather than something Measure-specific? Will it not fail the same way wheresoever it's included?

**Comment by grooverdan** [comment]
yes, its just a sqlite library issue.

For Measure, its just one we can avoid.
